btop: Autospec creation for update from version 1.3.0 to version 1.3.1
Helmut K. C. Tessarek (1):
      fix: increase interface name length to 15

Jakob P. Liljenberg (1):
      Update README.md -> Fixed bad links

Jos Dehaes (1):
      fix: don't mangle memory for zombie processes

Laurent Cheylus (1):
      Check LC_CTYPE to set UTF-8 locale

Martin Oliver Pitoňák (3):
      btop now reacts to SIGUSR1 by reloading config
      SIGUSR2 signal now reloads the config
      added ctrl+r shortcut to reload config from disk

Mathieu Sviridov (1):
      Add theme based on Everforest Dark Medium palette

Steffen Winter (10):
      Bump cmake to v1.3.0
      Use _FORTIFY_SOURCE=3 and put it behind a build flag
      Fix abort in locale detection on OpenBSD
      Allow the Findkvm module on all BSDs
      CMake: Enable OpenBSD
      Make BTOP_DEBUG also work for CMake
      -DFMT_HEADER_ONLY as a compiler flag
      cmake: Fix undefined reference to `kvm_openfiles' on BSD's
      bsd: Wrap kvm_t* in a uniq_ptr and share code between BSD's
      collect: Share ifaddrs wrapper and use uniq_ptr-like syntax

Steven Ward (1):
      Write newline at end of config file

aristocratos (8):
      Added link to compile section
      Undefine FORTIFY_SOURCE before setting new value when enabled
      Support for dynamic loading of ROCm v6
      Added continuous build for testing Gpu support
      Fix dependencies for Continuous Build Gpu
      Fixed incorrect used and available memory for OSX
      Reuse code from init, properly log warnings and move execution in to main loop
      v1.3.1 Bug fixes

fxzjshm (1):
      Fix dynamic loading of ROCm v6

jkre (18):
      Add current_now and voltage_now to battery struct and fix naming of
      Introduce charge in addition to energy for laptops that use charge instead of energy, this is done so that the units make more sense in this case
      add case of calculating the remaining battery time for current/charge
      add battery percentage calculation in charge case
      use capacity as default for battery percentage, less complicated and matches desktop percent exactly
      clean up if statement for battery percent calculation
      add power draw calculation for battery
      add power to get_battery function output
      Show wattage next to battery remaining time when wattage could be calculated
      remove redundant space
      round wattage to second decimal
      add show_battery_power option to menu
      Only redraw battery indicator on power change if power change option is set to true
      make discribtion in menu and settings clearer
      add freebsd support for battery power
      make os compatible
      Add battery power draw to battery inforamtion tuple for openbsd and set it to a constant
      Fix missing value in battery status tuple for openbsd

rliang (1):
      Fix basic_string::_M_create exception

v4u6h4n (1):
      Update README.md